### ISSUE TITLE
grammatical mistake involving unnecessary comma

### ISSUE THREAD

**Issue by nmpham2** [ChaseC99/chasec99.github.io#1]
https://github.com/ChaseC99/chasec99.github.io/blob/90cba48b92b68896f10f97cb25bb63a14d3d94b8/index.html#L79

Use commas after introductory a) clauses, b) phrases, or c) words that come before the main clause.

Here, I have attached a link to a quick guide on commas, which should be useful for you.
https://owl.purdue.edu/owl/general_writing/punctuation/commas/index.html

**Comment by ChaseC99** [comment]
I'm so embarrassed. 
Resolved in commit c667881
